[package]
name = "enigo"
version = "0.2.0-rc2"
authors = [
    "pentamassiv <pentamassiv@posteo.de>",
    "Dustin Bensing <dustin.bensing@googlemail.com>",
]
edition = "2021"
rust-version = "1.71"
description = "Cross-platform (Linux, Windows & macOS) library to simulate keyboard and mouse events"
documentation = "https://docs.rs/enigo/"
homepage = "https://github.com/enigo-rs/enigo"
repository = "https://github.com/enigo-rs/enigo"
readme = "README.md"
keywords = ["simulate", "input", "mouse", "keyboard", "automation"]
categories = [
    "development-tools::testing",
    "api-bindings",
    "hardware-support",
    "os",
    "simulation",
]
license = "MIT"
exclude = [".github", "examples", ".gitignore", "rustfmt.toml"]

[package.metadata.docs.rs]
all-features = true

[features]
default = ["xdo"]
serde = ["dep:serde"]
wayland = [
    "dep:wayland-client",
    "dep:wayland-protocols-misc",
    "dep:wayland-protocols-wlr",
    "dep:wayland-protocols-plasma",
    "dep:tempfile",
]
xdo = []

[dependencies]
log = "0.4"
serde = { version = "1", features = ["derive"], optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.51", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
] }

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = { version = "0.23", features = ["highsierra"] }
icrate = { version = "0.1.0", features = ["AppKit_all"] }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
wayland-protocols-misc = { version = "0.2", features = [
    "client",
], optional = true }
wayland-protocols-wlr = { version = "0.2", features = [
    "client",
], optional = true }
wayland-protocols-plasma = { version = "0.2", features = [
    "client",
], optional = true }
wayland-client = { version = "0.31", optional = true }
x11rb = { version = "0.13", features = [
    "randr",
    "xinput",
    "xtest",
], optional = true }
xkbcommon = "0.7"
xkeysym = "0.2"
tempfile = { version = "3", optional = true }

[dev-dependencies]
env_logger = "0.10"
tungstenite = "0.21"
url = "2"
webbrowser = "0.8"
ron = "0.8"

[[example]]
name = "serde"
path = "examples/serde.rs"
required-features = ["serde"]
