[package]
name = "enigo"
version = "0.0.14"
authors = ["Dustin Bensing <dustin.bensing@googlemail.com>"]
edition = "2021"
build = "build.rs"
rust-version = "1.64"

description = "Enigo lets you control your mouse and keyboard in an abstract way on different operating systems (currently only Linux, macOS, Win â€“ Redox and *BSD planned)"
documentation = "https://docs.rs/enigo/"
homepage = "https://github.com/enigo-rs/enigo"
repository = "https://github.com/enigo-rs/enigo"
readme = "README.md"
keywords = ["input", "mouse", "testing", "keyboard", "automation"]
categories = ["development-tools::testing", "api-bindings", "hardware-support"]
license = "MIT"

[badges]
travis-ci = { repository = "enigo-rs/enigo" }
appveyor = { repository = "pythoneer/enigo-85xiy" }

[dependencies]
serde = { version = "1.0.102", optional = true }
serde_derive = { version = "1.0.102", optional = true }

[dev-dependencies]
tungstenite = "0.18.0"
url = "2.3.1"
webbrowser = "0.8.6"

[features]
with_serde = ["serde", "serde_derive"]

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.44.0", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
] }

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = "0.18.0"
objc = "0.2.7"
unicode-segmentation = "1.6.0"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2.65"

[build-dependencies]
pkg-config = "0.3.17"
