[package]
name = "enigo"
version = "0.1.2"
authors = ["Dustin Bensing <dustin.bensing@googlemail.com>"]
edition = "2021"
build = "build.rs"
rust-version = "1.64"

description = "Enigo lets you control your mouse and keyboard in an abstract way on different operating systems (currently only Linux, macOS, Win â€“ Redox and *BSD planned)"
documentation = "https://docs.rs/enigo/"
homepage = "https://github.com/enigo-rs/enigo"
repository = "https://github.com/enigo-rs/enigo"
readme = "README.md"
keywords = ["input", "mouse", "testing", "keyboard", "automation"]
categories = ["development-tools::testing", "api-bindings", "hardware-support"]
license = "MIT"

exclude = [
    ".github",
    ".vscode",
    "examples",
    ".gitignore",
    "CHANGES.md",
    "rustfmt.toml",
]

[dependencies]
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }

[dev-dependencies]
tungstenite = "0.20"
url = "2.3"
webbrowser = "0.8"

[features]
with_serde = ["serde", "serde_derive"]

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.48", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
] }

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = { version = "0.23", features = ["highsierra"] }
objc = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3"
