name: Build

permissions:
  contents: read
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}


env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUST_LOG: debug
  WAYLAND_DEBUG: 1
  REIS_DEBUG: 1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - nightly
          - "1.87.0"
        platform:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        features:
          - "libei,tokio,wayland,xdo,x11rb,xdg_desktop"
          - "libei,smol,wayland,xdo,x11rb,xdg_desktop"
          - "default"
          - "libei,tokio"
          - "libei,smol"
          - "wayland"
          - "xdo"
          - "x11rb"
          - "xdg_desktop,tokio"
          - "xdg_desktop,smol"
        exclude:
          - platform: windows-latest
            features: "libei,tokio,wayland,xdo,x11rb,xdg_desktop"
          - platform: windows-latest
            features: "libei,smol,wayland,xdo,x11rb,xdg_desktop"
          - platform: windows-latest
            features: "libei,tokio"
          - platform: windows-latest
            features: "libei,smol"
          - platform: windows-latest
            features: "wayland"
          - platform: windows-latest
            features: "xdo"
          - platform: windows-latest
            features: "x11rb"
          - platform: windows-latest
            features: "xdg_desktop,tokio"
          - platform: windows-latest
            features: "xdg_desktop,smol"
          - platform: macos-latest
            features: "libei,tokio,wayland,xdo,x11rb,xdg_desktop"
          - platform: macos-latest
            features: "libei,smol,wayland,xdo,x11rb,xdg_desktop"
          - platform: macos-latest
            features: "libei,tokio"
          - platform: macos-latest
            features: "libei,smol"
          - platform: macos-latest
            features: "wayland"
          - platform: macos-latest
            features: "xdo"
          - platform: macos-latest
            features: "x11rb"
          - platform: macos-latest
            features: "xdg_desktop,tokio"
          - platform: macos-latest
            features: "xdg_desktop,smol"
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/install_deps
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Check the code format
        if: matrix.rust == 'nightly' # Avoid differences between the versions
        run: cargo fmt -- --check

      - name: Check clippy lints
        run: cargo clippy --no-default-features --features ${{ matrix.features }} -- -D clippy::pedantic
      - name: Check clippy lints for the examples
        run: cargo clippy --no-default-features --features ${{ matrix.features }} --examples -- -D clippy::pedantic

      - name: Build the code
        run: cargo build --no-default-features --features ${{ matrix.features }}

      - name: Build the docs
        run: cargo doc --no-deps --no-default-features --features ${{ matrix.features }}

      - name: Build the examples
        run: cargo build --examples --no-default-features --features ${{ matrix.features }}

      - name: Build the examples in release mode
        run: cargo build --release --examples --no-default-features --features ${{ matrix.features }}