name: Test

permissions:
  contents: read
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUST_LOG: debug
  WAYLAND_DEBUG: 1
  REIS_DEBUG: 1

jobs:
  test:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}  # Only run if the build succeeded
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - nightly
          - "1.85.0"
        platform:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        features: 
          # The tests will fail on Ubuntu for libei and wayland, because the compositor of the Github runner does not support it
          #- "libei_tokio,wayland,xdo,x11rb"
          #- "libei_smol,wayland,xdo,x11rb"
          - "default"
          #- "libei_tokio"
          #- "libei_smol"
          #- "wayland"
          - "xdo"
          - "x11rb"
        exclude:
          # The implementation on Windows and macOS does not have any features so we can reduce the number of combinations
          #- platform: windows-latest
          #  features: "libei_tokio,wayland,xdo,x11rb"
          #- platform: windows-latest
          #  features: "libei_smol,wayland,xdo,x11rb"
          #- platform: windows-latest
          #  features: "libei_tokio"
          #- platform: windows-latest
          #  features: "libei_smol"
          #- platform: windows-latest
          #  features: "wayland"
          - platform: windows-latest
            features: "xdo"
          - platform: windows-latest
            features: "x11rb"
          #- platform: macos-latest
          #  features: "libei_tokio,wayland,xdo,x11rb"
          #- platform: macos-latest
          #  features: "libei_smol,wayland,xdo,x11rb"
          #- platform: macos-latest
          #  features: "libei_tokio"
          #- platform: macos-latest
          #  features: "libei_smol"
          #- platform: macos-latest
          #  features: "wayland"
          - platform: macos-latest
            features: "xdo"
          - platform: macos-latest
            features: "x11rb"
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6
        with:
          # If manually triggered, use the current commit (GITHUB_SHA), otherwise use the head_sha from the Build workflow
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}
      - uses: ./.github/actions/install_deps
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Setup headless display for tests on Linux
        if: runner.os == 'Linux' # This step is only needed on Linux. The other OSs don't need to be set up
        uses: ./.github/actions/headless_display

      - name: Install Firefox on macOS
        if: runner.os == 'macOS'
        run: brew install --cask firefox

      - name: Run the unit tests
        run: cargo test unit --no-default-features --features ${{ matrix.features }} -- --test-threads=1 --nocapture
      
      - name: Run the unit tests in release mode
        run: cargo test unit --release --no-default-features --features ${{ matrix.features }} -- --test-threads=1 --nocapture

      - name: Run the sync example
        run: cargo run --example sync --no-default-features --features ${{ matrix.features }}
